# Generated by Django 3.1.3 on 2021-02-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210217_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='slug',
        ),
    ]
