# Generated by Django 3.1.3 on 2020-12-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
