# Generated by Django 3.1.3 on 2020-12-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
