# Generated by Django 3.1.3 on 2020-12-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20201210_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
