# Generated by Django 3.1.3 on 2020-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20201210_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
